kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd-dynamic-class
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.16.64.13:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  pool: kube
  userId: admin
  userSecretName: ceph-secret-admin
