- name: 解压harbor-offline-installer-v1.6.0-rc2.tgz
  shell: "tar -zxvf /etc/ansible/down/harbor-offline-installer-v1.5.2.tgz -C /etc/ansible/down/"

- name: 配置harbor.cfg
  template: src=harbor.cfg.j2 dest=/etc/ansible/down/harbor/harbor.cfg

- name: 配置docker-compose.yml
  template: src=docker-compose.yml.j2 dest=/etc/ansible/down/harbor/docker-compose.yml

- name: 配置docker-compose.clair.yml
  template: src=docker-compose.clair.yml.j2 dest=/etc/ansible/down/harbor/docker-compose.clair.yml

- name: 配置docker-compose.notary.yml
  template: src=docker-compose.notary.yml.j2 dest=/etc/ansible/down/harbor/docker-compose.notary.yml

- name: 安装docker-compose
  shell: "yum install -y python-pip &&\
        pip install -U docker-compose"

- name: 执行install.sh
  shell: "/etc/ansible/down/harbor/install.sh"

- name: 安装harbor
  shell: "docker-compose -f /etc/ansible/down/harbor/docker-compose.yml start"
